version: "3"
services:
  todofront:
    build: todofrontend
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    networks:
      - rede-virtual
  todoback:
    build: todobackend
    restart: on-failure
    ports:
      - 3001:3001
    networks:
      - rede-virtual
  todotests:
    build: todotests
    restart: on-failure
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
    networks:
      - rede-virtual

networks:
  rede-virtual: